name: React CI

on:
  push:
    branches:
      - develop
      - Feature/*
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        working-directory: ./frontend
        run: |
          yarn install
          yarn build
          yarn test

        env:
          CI: false
          working-directory: ./frontend
